//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamIdler.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamIdler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete your account?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AccountDeletionConfirmationPhrase {
            get {
                return ResourceManager.GetString("AccountDeletionConfirmationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add App과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddApp {
            get {
                return ResourceManager.GetString("AddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppId {
            get {
                return ResourceManager.GetString("AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AppList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppList {
            get {
                return ResourceManager.GetString("AppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppSearch {
            get {
                return ResourceManager.GetString("AppSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AutomaticLogin {
            get {
                return ResourceManager.GetString("AutomaticLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Logon denied. Need two-factor code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_AccountLoginDeniedNeedTwoFactor {
            get {
                return ResourceManager.GetString("Description_AccountLoginDeniedNeedTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account logon denied과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_AccountLogonDenied {
            get {
                return ResourceManager.GetString("Description_AccountLogonDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account logon denied. Verified email required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_AccountLogonDeniedVerifiedEmailRequired {
            get {
                return ResourceManager.GetString("Description_AccountLogonDeniedVerifiedEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while adding the app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_AddAppError {
            get {
                return ResourceManager.GetString("Description_AddAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while deleting the app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_DeleteAppError {
            get {
                return ResourceManager.GetString("Description_DeleteAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth code is not correct과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_InvalidLoginAuthCode {
            get {
                return ResourceManager.GetString("Description_InvalidLoginAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is not valid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_InvalidPassword {
            get {
                return ResourceManager.GetString("Description_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while loading accounts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_LoadAccountsError {
            get {
                return ResourceManager.GetString("Description_LoadAccountsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while loading the app과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_LoadAppsError {
            get {
                return ResourceManager.GetString("Description_LoadAppsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two-factor code is not correct과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description_TwoFactorCodeMismatch {
            get {
                return ResourceManager.GetString("Description_TwoFactorCodeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Logged In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logged In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove App과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveApp {
            get {
                return ResourceManager.GetString("RemoveApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SignInAll {
            get {
                return ResourceManager.GetString("SignInAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartIdling과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StartIdling {
            get {
                return ResourceManager.GetString("StartIdling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steam Idler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SteamIdler {
            get {
                return ResourceManager.GetString("SteamIdler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two Factor Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
